import { makeStyles } from '@material-ui/core/styles'
export const useStyles = makeStyles((theme) => ({
  // ############# token_sale_coming_soon_div ############# //
  token_sale_coming_soon_div: {
    width: '48rem',
    height: '37.3rem',
    background: '#fff',
    backdropFilter: 'blur(20px)',
    borderRadius: '2rem',
    [theme.breakpoints.down('sm')]: {
      marginTop: '5rem',
    },
  },
  trip_token_info: {
    width: '100%',
    height: '14rem',
    background: '#21D1CC',
    backdropFilter: 'blur(20px)',
    borderRadius: '2rem',
    padding: '0 4rem',
    boxSizing: 'border-box',
    display: 'flex',
    // justifyContent: 'center',
    alignItems: 'center',
  },
  trip_token_details: {
    marginLeft: '1.4rem',
    display: 'flex',
  },
  one_trip_token_info: {
    display: 'flex',
    alignItems: 'center',
    '&> h2': {
      fontFamily: 'IBMPlexSansBold',
      fontSize: '4rem',
      lineHeight: '4.8rem',
      color: '#1C232B',
      width: '2.4rem',
      height: '4.8rem',
    },
    '& > p': {
      marginLeft: '.6rem',
      width: '4.9rem',
      height: '3.4rem',
      fontFamily: 'InterRegular',
      fontSize: '1.2rem',
      lineHeight: '1.68rem',
      textTransform: 'uppercase',
      color: 'rgba(28, 35, 43, .5)',
    },
  },
  trip_token_details_equal_symbol: {
    margin: '0 4.9rem',
  },
  trip_token_usd_price: {
    fontFamily: 'IBMPlexSansBold',
    fontSize: '4rem',
    lineHeight: '4.8rem',
    color: ' #1C232B',
  },
  brief_case_icon_div: {
    width: '8rem',
    height: '8rem',
    background: '#ECF4F4',
    border: '2px solid #FFFFFF',
    boxSizing: 'border-box',
    borderRadius: '200px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    '& > img': {
      height: '3.666653823852539rem',
      width: '3.8420013427734375rem',
    },
  },
  sales_start_in_info_container: {
    padding: '3rem 4rem 3rem 3.3rem',
  },
  sales_start_in_info: {
    width: '40.7rem',
    height: '11.5rem',
    border: '1px solid rgba(55, 65, 106, .2)',
    boxSizing: 'border-box',
    borderRadius: '2rem',
    padding: '2rem 0',
  },
  sales_start_text: {
    fontFamily: 'IBMPlexSansSemiBold',
    fontSize: '1.4rem',
    lineHeight: '1.7rem',
    textAlign: 'center',
    color: ' #37416A',
  },
  sales_start_time: {
    marginTop: '1rem',
    fontFamily: 'IBMPlexSansBold',
    fontSize: '4rem',
    lineHeight: '4.8rem',
    textAlign: 'center',
    color: ' #1C232B',
  },
  sales_button: {
    marginTop: '1rem',
    width: '100%',
    height: '4.8rem',
    background: 'rgba(33, 209, 204, 0.5)',
    borderRadius: '.6rem',
    outline: '0',
    border: '0',
    cursor: 'pointer',
    fontFamily: 'InterSemiBold',
    fontSize: '1.4rem',
    lineHeight: '1.7rem',
    textAlign: 'center',
    color: ' #FFFFFF',
  },
}))
